version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # persist models

  streamlit:
    build: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"   # internal DNS resolves "ollama"

volumes:
  ollama_data:

